In [1]:
import numpy as np

In [2]:
ar1 = np.array([[1,2,3],
            [4,5,6]])

In [3]:
ar1.sum(axis=0)

array([5, 7, 9])

In [4]:
b = np.array([[1,0,3],
            [4,5,9]])

In [5]:
ar1.dot(b.transpose())

array([[10, 41],
       [22, 95]])

In [6]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [7]:
np.cross(ar1,b)

array([[  6,   0,  -2],
       [ 15, -12,   0]])

In [8]:
np.sort(ar1)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.sort(b)

array([[0, 1, 3],
       [4, 5, 9]])

In [10]:
np.sort(b, axis=0)

array([[1, 0, 3],
       [4, 5, 9]])

## Argument SOrt

In [11]:
c = np.arange(6)

In [12]:
c

array([0, 1, 2, 3, 4, 5])

In [16]:
b1 = np.array([1,151,51,5,1,5,1,51,451,3,8,1,4,35,1,34,8,5])
b1 = b1.reshape(9,2)

In [17]:
b1

array([[  1, 151],
       [ 51,   5],
       [  1,   5],
       [  1,  51],
       [451,   3],
       [  8,   1],
       [  4,  35],
       [  1,  34],
       [  8,   5]])

In [19]:
np.argsort(b1)

array([[0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0]], dtype=int64)

## Start of Pandas