In [2]:
import numpy as np
array1 = np.array([3,5,1])
print(type(array1))

<class 'numpy.ndarray'>


In [3]:
array1.shape

(3,)

In [5]:
array1.dtype

dtype('int32')

In [10]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones(6).dtype

dtype('float64')

In [16]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
array1*array1

array([ 9, 25,  1])

In [23]:
array1**array1

array([  27, 3125,    1])

## SLicing

In [28]:
array1

array([3, 5, 1])

In [31]:
array1[4:6]

array([], dtype=int32)